INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('apple', 55);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('pen', 22);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('penapple', 2255);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('applepen', 5522);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('penapplepen', 225522);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('penpenappleapplepen', 222255552);